import React, { useState } from 'react';
import { Send, Loader2, Sparkles, HelpCircle, RefreshCw } from 'lucide-react';

interface InputFormProps {
  onSubmit: (answer: string, question?: string) => void;
  onLoadDemo: () => void;
  isLoading: boolean;
}

const PRESET_EXAMPLES = [
  {
    label: "DNA Discovery (Watson & Franklin)",
    question: "Tell me about the discovery and structure of DNA, including key contributors and dates.",
    answer: "The double helix structure of DNA was discovered in 1953 by James Watson and Francis Crick. Rosalind Franklin's Photo 51 was critical in determining the helical structure, though she was awarded the Nobel Prize in 1962 alongside them. The human genome contains approximately 3.2 billion base pairs."
  },
  {
    label: "Space Exploration (Apollo 11)",
    question: "When did Apollo 11 land on the moon?",
    answer: "Apollo 11 landed on the Moon on July 20, 1969. Neil Armstrong and Buzz Aldrin explored the lunar surface. Apollo 11 was launched aboard a Saturn I rocket."
  },
  {
    label: "Invention of Telephone",
    question: "Who invented the telephone?",
    answer: "Alexander Graham Bell was awarded the first US patent for the telephone in 1876. Thomas Edison invented the telephone in 1910."
  }
];

export const InputForm: React.FC<InputFormProps> = ({ onSubmit, onLoadDemo, isLoading }) => {
  const [answer, setAnswer] = useState(PRESET_EXAMPLES[0].answer);
  const [question, setQuestion] = useState(PRESET_EXAMPLES[0].question);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!answer.trim() || isLoading) return;
    onSubmit(answer.trim(), question.trim() || undefined);
  };

  const handleSelectPreset = (preset: typeof PRESET_EXAMPLES[0]) => {
    setQuestion(preset.question);
    setAnswer(preset.answer);
  };

  return (
    <div className="bg-slate-900/90 border border-slate-800 rounded-xl p-5 shadow-xl">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-4">
        <div>
          <h2 className="text-base font-semibold text-white flex items-center gap-2">
            Verify AI-Generated Answer
          </h2>
          <p className="text-xs text-slate-400">
            Paste any draft text generated by an LLM to extract atomic claims and check against external evidence.
          </p>
        </div>

        {/* Demo Fast-Load Button */}
        <button
          type="button"
          onClick={onLoadDemo}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-emerald-950/60 text-emerald-300 border border-emerald-700/60 hover:bg-emerald-900/80 transition-all shadow-sm self-start sm:self-auto"
        >
          <Sparkles className="h-3.5 w-3.5 text-emerald-400" />
          <span>Load Demo Example (Offline Cache)</span>
        </button>
      </div>

      {/* Preset pills */}
      <div className="flex flex-wrap items-center gap-2 mb-3">
        <span className="text-xs text-slate-400 font-medium">Quick Presets:</span>
        {PRESET_EXAMPLES.map((preset, idx) => (
          <button
            key={idx}
            type="button"
            onClick={() => handleSelectPreset(preset)}
            className="text-xs px-2.5 py-1 rounded-md bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700/60 transition-colors"
          >
            {preset.label}
          </button>
        ))}
      </div>

      <form onSubmit={handleSubmit} className="space-y-3.5">
        <div>
          <label className="block text-xs font-medium text-slate-300 mb-1 flex items-center gap-1.5">
            <HelpCircle className="h-3.5 w-3.5 text-slate-400" />
            Prompt / Question (Optional)
          </label>
          <input
            type="text"
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            placeholder="e.g. Tell me about the discovery and structure of DNA..."
            className="w-full px-3 py-2 rounded-lg bg-slate-950 border border-slate-800 text-sm text-slate-200 placeholder-slate-500 focus:outline-none focus:ring-1 focus:ring-emerald-500 focus:border-emerald-500"
          />
        </div>

        <div>
          <label className="block text-xs font-medium text-slate-300 mb-1">
            AI-Generated Answer Text to Verify <span className="text-rose-400">*</span>
          </label>
          <textarea
            rows={4}
            value={answer}
            onChange={(e) => setAnswer(e.target.value)}
            required
            placeholder="Enter or paste the AI draft answer containing factual claims..."
            className="w-full px-3.5 py-2.5 rounded-lg bg-slate-950 border border-slate-800 text-sm text-slate-200 placeholder-slate-500 focus:outline-none focus:ring-1 focus:ring-emerald-500 focus:border-emerald-500 leading-relaxed font-sans"
          />
        </div>

        <div className="flex items-center justify-between pt-1">
          <button
            type="button"
            onClick={() => { setAnswer(""); setQuestion(""); }}
            className="text-xs text-slate-400 hover:text-slate-200 flex items-center gap-1"
          >
            <RefreshCw className="h-3 w-3" />
            Clear
          </button>

          <button
            type="submit"
            disabled={isLoading || !answer.trim()}
            className="inline-flex items-center gap-2 px-5 py-2 rounded-lg text-sm font-semibold bg-emerald-500 hover:bg-emerald-400 text-slate-950 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-md shadow-emerald-500/20"
          >
            {isLoading ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin text-slate-950" />
                <span>Verifying claims...</span>
              </>
            ) : (
              <>
                <Send className="h-4 w-4 text-slate-950" />
                <span>Verify Claims</span>
              </>
            )}
          </button>
        </div>
      </form>
    </div>
  );
};
